import Head from "next/head";

import Hero from "../components/Hero";
import Separator from "../components/Separator";
import MyProjects from "../components/MyProjects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lucero Amaolo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Separator text="My projects" />
        <MyProjects />
        <Separator text="Contact me" />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
