import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { Slant as Hamburger } from "hamburger-react";

import Menu from "../components/Menu";
import Hero from "../components/Hero";

import styles from "../styles/Home.module.css";
import Separator from "../components/Separator";
import MyProjects from "../components/MyProjects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Lucero Amaolo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${styles.header} ${isMenuOpen ? styles.noBg : null}`}>
        <div>
          <Link href="/">lamaolo</Link>
          <Hamburger
            color="white"
            toggled={isMenuOpen}
            toggle={setIsMenuOpen}
          ></Hamburger>
        </div>
      </header>
      <main className={styles.container}>
        <Hero />
        <Separator text="My projects" />
        <MyProjects />
        <Separator text="Contact me" />
        <Contact />
        <Footer />
      </main>
      {isMenuOpen ? <Menu /> : null}
    </>
  );
}
