import { useState } from "react";
import Head from "next/head";
import { Slant as Hamburger } from "hamburger-react";
import Link from "next/link";

import Menu from "../components/Menu";
import Hero from "../components/Hero";

import styles from "../styles/Home.module.css";
import Separator from "../components/Separator";
import MyProjects from "../components/MyProjects";

export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Lucero Amaolo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <header className={styles.header}>
          <Link href="/">lamaolo</Link>
          <Hamburger
            color="white"
            toggled={isMenuOpen}
            toggle={setIsMenuOpen}
          ></Hamburger>
        </header>
        <Hero />
        <Separator text="My projects" />
        <MyProjects />
      </main>
      {isMenuOpen ? <Menu /> : null}
    </>
  );
}
